# Generated by Django 5.1.7 on 2025-06-13 20:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_remove_waternetwork_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waternetwork",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Water Network",
                "verbose_name_plural": "Water Networks",
            },
        ),
        migrations.AddField(
            model_name="waternetwork",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="waternetwork",
            name="link_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number of Links"
            ),
        ),
        migrations.AddField(
            model_name="waternetwork",
            name="node_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number of Nodes"
            ),
        ),
        migrations.AddField(
            model_name="waternetwork",
            name="pressure_limit",
            field=models.FloatField(
                default=30.0, verbose_name="Maximum Pressure Limit (m)"
            ),
        ),
        migrations.AddField(
            model_name="waternetwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing"),
                    ("analyzed", "Analyzed"),
                    ("error", "Error"),
                ],
                default="uploaded",
                max_length=20,
                verbose_name="Analysis Status",
            ),
        ),
        migrations.AddField(
            model_name="waternetwork",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="water_networks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uploaded By",
            ),
        ),
        migrations.AlterField(
            model_name="waternetwork",
            name="file",
            field=models.FileField(
                upload_to="networks/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["inp"]
                    )
                ],
                verbose_name="EPANET .inp File",
            ),
        ),
        migrations.AlterField(
            model_name="waternetwork",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Network Name"),
        ),
        migrations.AlterField(
            model_name="waternetwork",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Upload Date"),
        ),
    ]
